### ISSUE TITLE
puppet is updating logicmonitor using PUT instead of PATCH

### ISSUE THREAD

**Issue by bjmgeek** [logicmonitor/logicmonitor-puppet-v4#14]
I have a system that I set custom properties on in the web interface of logicmonitor. However, every time puppet runs, they are overwritten.  I can see the following entries in the audit log :

Here's the log of the original modifications, made by user patrick:

XXXXXXXXXXXXXXXXXXXXX | patrick | 1521834772 | 2018-03-23 15:52:52 EDT | 174.XXX.XXX.XXX | 2C84830FE08F33B989F903CA028303D1 | Update host<2408, bonnie.example.com> (monitored by collector <53, heatherlee.example.com>), [Added property (jdbc.postgres.dbname:mydbname)] [Added property (jdbc.postgres.pass:********)] [Added property (system.categories:snmpTCPUDP,Netsnmp,snmpHR,snmp)]

And a few minutes later, puppet runs, and generates this audit log:
XXXXXXXXXXXXXXXXXXX | sysmaint | 1521835027 | 2018-03-23 15:57:07 EDT | 198.XXX.XXX.XXX |   | Update host bonnie.stockpile.nemgint.com, [Modified property puppet.update.on: 2018-03-23T15:24:18-04:00 -> 2018-03-23T15:57:07-04:00] [Deleted property jdbc.postgres.dbname] [Deleted property jdbc.postgres.pass] [Deleted property system.categories] , Remove Host From HostGroup : Linux Servers.  via API token XXXXXXXXXXXXXX

Here's the puppet code that's triggering the issue:

````
class profile::monitoring(
    String $collector,
    String $contact,
    String $location,
    Boolean $manage_snmp            = false,
    String $snmp_service_ensure     = 'running',
    String $snmp_network            = '0.0.0.0/0',
    Array[String] $snmp_ports       = [ 'udp:161' ],
    Array[String] $device_groups    = []
) {
  
    # generate a unique community per host 
    $snmp_community = pw_hash($uuid, 'SHA-256', regsubst($hostname, '[^A-Za-z]', ''))

    class { 'logicmonitor::device': 
        collector   => $collector,
        groups      => sort($device_groups),
        properties  => {
            "snmp.community" => $snmp_community
        }
    }
    
    if $manage_snmp {

        class { 'snmp':
            agentaddress   => $snmp_ports,
            ro_community   => $snmp_community,
            ro_community6  => $snmp_community,
            ro_network     => $snmp_network,
            contact        => $contact,
            location       => $location,
            service_ensure => $snmp_service_ensure,
            snmpd_config   => [ 'extend lm-inodes /bin/df -ilTP -x tmpfs' ]
        }
    }

}

````

This is the relevant section of YAML for the host: (generated by foreman, which is used as an external node classifier)
````
---
classes:
  profile::monitoring:
    collector: mycollector.example.com
    contact: sysadmins@example.com.com
    device_groups:
    - Servers/XXXXXX/Production/CentOS
    - Servers/Backend/Postgres/Main/Production
    location: XXXXXXX/Production
    manage_snmp: true
parameters:
  puppetmaster: puppet.example.com
  domainname: mydomain.example.com
  foreman_domain_description: ''
  hostgroup: XXXXXX/Servers/Backend/Postgres/Main/Production
  location: Production
  location_title: Tierpoint/Production
````
